### ISSUE TITLE
커스텀 카메라 UI 만들기

### ISSUE THREAD

**Issue by wisemuji** [Coveong/coveong-bank-account-scanner#10]
## Description
> 커스텀 카메라 UI 만들기

## To-do
* [ ] 커스텀 카메라 뷰 생성
* [ ] 뷰에 특정 영역 표시
* [ ] 촬영 이벤트 연결
