### ISSUE TITLE
카메라 이벤트 연결

### ISSUE THREAD

**Issue by wisemuji** [Coveong/coveong-bank-account-scanner#15]
## Description
> 카메라에서 사진을 찍으면 메인 화면에서 확인할 수 있도록 구현

## To-do
* [x] 카메라 이벤트를 수신하여 메인 화면 사진에 표시
* [x] 테스트 이미지를 실제 이미지로 연결
* [x] 카메라 해상도 이슈 해결
