### ISSUE TITLE
이미지 인식 request api 개발

### ISSUE THREAD

**Issue by shinsunyoung** [Coveong/coveong-bank-account-scanner#8]
## Description
> 이미지를 base64로 인코딩하고 google vision api에 요청하는 코드 추가

## To-do
* [x] 인증키 properties에 넣고 gitignore에서 수정
* [x] 이미지 base64로 인코딩
* [x] google vision api에 요청
